### ISSUE TITLE
Infinite loop in IPDecoder.FilterAndStoreData when IPv4 length and ID fields are both 0

### ISSUE THREAD

**Issue by apmorton** [ravahn/machina#13]
I have observed this behavior on my machine.

machina will infinite loop, consuming excessive cpu resources and ballooning memory over time as the `NetworkBufferFactory` is no longer being dequeue'd from.

When debugged I can observe the following packet data causing the issue:

```
45 00 00 00 00 00 40 00 80 06 00 00 0a 01 32 40 0a 00 32 68 10 a2 01 bd a3 75 84 3a 54 70 42 31 50 10 60 dc 78 af 00 00 ca d7
```
(I have trimmed the remainder of the payload for brevity)

If you prepend a fake ethernet header and decode it on https://hpd.gasmi.net/ you can see the issue.
```
01 00 0C CC CC CD 00 50 3E B4 E4 66 08 00 45 00 00 00 00 00 40 00 80 06 00 00 0A 01 32 40 0A 00 32 68 10 A2 01 BD A3 75 84 3A 54 70 42 31 50 10 60 DC 78 AF 00 00 CA D7
```

This is valid netbios traffic that happens to have an IPv4 header containing 0 length and 0 ID, so the following happens:

`packetLength` remains 0
https://github.com/ravahn/machina/blob/e382b6b6f9b1cdcaff8e8c311c7dfe70f4a6201f/Machina/IPDecoder.cs#L132-L134

 `offset` is unchanged
https://github.com/ravahn/machina/blob/e382b6b6f9b1cdcaff8e8c311c7dfe70f4a6201f/Machina/IPDecoder.cs#L160

the loop repeats on the same packet
https://github.com/ravahn/machina/blob/e382b6b6f9b1cdcaff8e8c311c7dfe70f4a6201f/Machina/IPDecoder.cs#L95-L98

I propose the check for `ip4Header.Id != 0` in the segment offload workaround be removed or an additional failsafe check similar to the following be added:
```C#
if (packetLength == 0) break;
```

**Comment by ravahn** [comment]
Apologies for the long delay in this bug.  I did some more reading on the .Id field and there does appear to be a RFC change to use .Id only for defragmentation / reassembly (RFC-6864) and relax its requirement to be >0, but I would need to do a lot more reading and careful testing before supporting Id=0 as a general case.

So, I made the choice to just add the failsafe check for packetLength == 0 to prevent the endless loop bug.  This was updated last year in the NetworkStructs branch, which is only now getting ready for merge back to Master branch.  I'll post an updated Nuget package when this is completed.
