### ISSUE TITLE
RawPCap_GetDataTwiceTest() failed if some network interface is down

### ISSUE THREAD

**Issue by Noisyfox** [ravahn/machina#2]
https://github.com/ravahn/machina/blob/9d648aa1d1174953fc44bad0e8471d28de8667bb/Machina.Tests/RawPCapTests.cs#L42

Will pick up the ip from an interface which is down then cause a null pointer ex at:

https://github.com/ravahn/machina/blob/9d648aa1d1174953fc44bad0e8471d28de8667bb/Machina/RawPCap.cs#L211

**Comment by Noisyfox** [comment]
This also affect the test RawSocket_GetDataTwiceTest() at
https://github.com/ravahn/machina/blob/9d648aa1d1174953fc44bad0e8471d28de8667bb/Machina/RawSocket.cs#L67

**Comment by ravahn** [comment]
thanks, I can fix that.

**Comment by ravahn** [comment]
Updated for 2.0.1 - the fix is to only include interfaces with status = Up in GetNetworkInterfaceIPs().  Let me know if it solved the problem for you.

**Comment by Noisyfox** [comment]
Cool~ It works now~
